version: '3.8'

services:
  auth_service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql-db:5432/Authdb
      SPRING_DATASOURCE_USERNAME: fitnest
      SPRING_DATASOURCE_PASSWORD: fitnest
      SPRING_APPLICATION_NAME: auth_service
    depends_on:
      - postgresql-db
    ports:
      - "8080:8080"

  postgresql-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: Authdb
      POSTGRES_USER: fitnest
      POSTGRES_PASSWORD: fitnest
    ports:
      - "5433:5432"

